apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-0731 
  janus-idp.io/tekton: test-0731
  backstage.io/kubernetes-id: test-0731
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-0731
resources: 
- application-dev.yaml